/**
 * Analysis Record - Data structure for storing analysis results
 * This interface defines all fields that will be saved to the database
 */
export interface AnalysisRecord {
    // Unique identifier (generated by database)
    id?: string;

    // Input data
    input_text: string | null;           // النص المُدخل
    image_description: string | null;    // وصف الصورة من النموذج
    has_image: boolean;                  // هل تم رفع صورة؟

    // Classification results
    classification: string;              // خطاب كراهية | محتوى غير كاره
    risk_level: string;                  // عالٍ | متوسط | منخفض | لا يوجد
    speech_type: string | null;          // نوع الخطاب (إهانة شخصية، وصم جماعي، إلخ)

    // Scores
    intensity_score: number;             // درجة الحدة (0-10)
    vulnerability_score: number;         // درجة الاستضعاف (0-5)
    context_score: number;               // درجة السياق (0-4)

    // Target information
    target_group: string | null;         // الفئة المستهدفة
    detected_markers: string[];          // المحددات اللغوية المكتشفة

    // Explanation
    rationale: string;                   // التفسير

    // Metadata
    locale: string;                      // ar | en | ku
    created_at: Date;                    // تاريخ ووقت التحليل

    // Optional: User feedback (if submitted later)
    user_feedback?: {
        correction: string;
        reasoning: string;
        submitted_at: Date;
    };
}

/**
 * Create a new AnalysisRecord from API response
 */
export function createAnalysisRecord(
    inputText: string | null,
    imageDescription: string | null,
    hasImage: boolean,
    apiResponse: {
        classification: string;
        risk_level: string;
        speech_type?: string;
        scores: {
            intensity: string | number;
            vulnerability: string | number;
            context: string | number;
        };
        target_group?: string;
        detected_markers?: string[];
        rationale?: string;
    },
    locale: string
): AnalysisRecord {
    // Parse score strings like "6/10" to numbers
    const parseScore = (val: string | number): number => {
        if (typeof val === 'number') return val;
        return parseInt(val.split('/')[0] || '0');
    };

    return {
        input_text: inputText,
        image_description: imageDescription,
        has_image: hasImage,
        classification: apiResponse.classification,
        risk_level: apiResponse.risk_level,
        speech_type: apiResponse.speech_type || null,
        intensity_score: parseScore(apiResponse.scores.intensity),
        vulnerability_score: parseScore(apiResponse.scores.vulnerability),
        context_score: parseScore(apiResponse.scores.context),
        target_group: apiResponse.target_group || null,
        detected_markers: apiResponse.detected_markers || [],
        rationale: apiResponse.rationale || '',
        locale,
        created_at: new Date()
    };
}

/**
 * Initiative Report - Data structure for user-submitted reports
 * Stored in a separate table, linked to AnalysisRecord
 */
export interface InitiativeReport {
    // Unique identifier (generated by database)
    id?: string;

    // Link to original analysis
    analysis_id: string;                 // ربط بالتحليل الأصلي

    // Report details
    post_url: string;                    // رابط المنشور
    reporter_country: string;            // بلد المُبلِّغ
    target_group_selected: string;       // الفئة المستهدفة (اختيار المستخدم)
    additional_info?: string;            // معلومات إضافية

    // Status tracking
    status: 'pending' | 'reviewed' | 'escalated' | 'closed';

    // Metadata
    submitted_at: Date;                  // تاريخ ووقت التبليغ
    reviewed_at?: Date;                  // تاريخ المراجعة
    reviewer_notes?: string;             // ملاحظات المراجع
}

/**
 * Create a new InitiativeReport
 */
export function createInitiativeReport(
    analysisId: string,
    postUrl: string,
    reporterCountry: string,
    targetGroup: string,
    additionalInfo?: string
): InitiativeReport {
    return {
        analysis_id: analysisId,
        post_url: postUrl,
        reporter_country: reporterCountry,
        target_group_selected: targetGroup,
        additional_info: additionalInfo,
        status: 'pending',
        submitted_at: new Date()
    };
}
